SYSTEM:
  NUM_WORKERS: 8
TRAIN:
  BACKBONE: resnet50
  BENCHMARK: coco
  BSZ: 16
  CATS_AUGMENTATIONS: true
  DECODER_LR: 0.0005
  DECODER_WEIGHT_DECAY: 0.0
  FOLD: 3
  IMG_SIZE: 417
  LR: 0.0005
  LR_SCHEDULER: constant
  MASK: true
  MILESTONES: null
  NITER: 400
  PFENET_AUGMENTATIONS: false
  WEIGHT_DECAY: 0.0
